name: CI/CD Pipeline

on:
  push:
  pull_request:
    branches:
      - master

jobs:


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install dependencies and build with Maven
        run: mvn clean install
        
      - name: Run tests
        run: mvn test
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install dependencies and build with Maven
        run: mvn clean install
        
      - name: Run tests
        run: mvn test

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v4.1.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "YOUR_HEROKU_APP_NAME"    
          heroku_email: "YOUR_HEROKU_ACCOUNT_EMAIL"  
          process_type: web
